//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.16 at 04:28:47 PM CST 
//


package com.github.tonygregg.flight;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.tonygregg.flight package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.tonygregg.flight
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteFlightDetailsResponse }
     * 
     */
    public DeleteFlightDetailsResponse createDeleteFlightDetailsResponse() {
        return new DeleteFlightDetailsResponse();
    }

    /**
     * Create an instance of {@link GetFlightDetailsRequest }
     * 
     */
    public GetFlightDetailsRequest createGetFlightDetailsRequest() {
        return new GetFlightDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllFlightDetailsRequest }
     * 
     */
    public GetAllFlightDetailsRequest createGetAllFlightDetailsRequest() {
        return new GetAllFlightDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteFlightDetailsRequest }
     * 
     */
    public DeleteFlightDetailsRequest createDeleteFlightDetailsRequest() {
        return new DeleteFlightDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllFlightDetailsResponse }
     * 
     */
    public GetAllFlightDetailsResponse createGetAllFlightDetailsResponse() {
        return new GetAllFlightDetailsResponse();
    }

    /**
     * Create an instance of {@link FlightDetails }
     * 
     */
    public FlightDetails createFlightDetails() {
        return new FlightDetails();
    }

    /**
     * Create an instance of {@link GetFlightDetailsResponse }
     * 
     */
    public GetFlightDetailsResponse createGetFlightDetailsResponse() {
        return new GetFlightDetailsResponse();
    }

}
